name: lts
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.8.10
  - pip=20.3
  - pytorch=2.2.0
  - pytorch-cuda=11.8
  - torchvision=0.17.0
  - cudatoolkit=11.8
  - numpy=1.19.2
  - pip:
    - scikit-learn==0.23.1
    - tqdm==4.62.3
    - wandb==0.12.0
    - ray[default]==2.9.0
    - ray[tune]==2.9.0
    - matplotlib==3.4.3
    - plotly==5.18.0
    - ml_collections
