config:
    # in distribution dataset
    id_dataset: "imagenet"
    # out-of-distribution datasets
    ood_datasets: ["inaturalist", "sun", "places", "textures"]
    # near
    # ood_datasets: ["ssb_hard", "ninco"]
    # far
    # ood_datasets: ["inaturalist"]
    # model
    model_name: "resnet50"
    # path to checkpoint from which to be restored
    train_restore_file: "resnet50-19c8e357.pth"
    # batch size
    batch_size: 200
    # scoring method
    scoring_method: "energy"
    # method
    method: "scale@85"
    
